name: practice-github-action
on: [ push ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh testing
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
        run: |
          echo "$HOSTNAME $USERNAME"
