name: practice-github-action
on: [ push ]
jobs:
  Explore-Github-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is first echo!"
        name: run1
      - run: echo "This is second echo!"